<div class="span-13" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <h1 property="name"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h1>

  <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
  <? if ($summary): ?>
    <p property="description">
      <?=$this->escapeHtml($this->truncate($summary, 300))?>
      <a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a>
    </p>
  <? endif; ?>

  <?/* Display Main Details */?>
  <table cellpadding="2" cellspacing="0" border="0" class="citation" summary="<?=$this->transEsc('Bibliographic Details')?>">
    <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Journal Title')?>:</th>
      <td>
        <a href="<?=$this->record($this->driver)->getLink('journaltitle', $journalTitle)?>"><?=$this->escapeHtml($journalTitle)?></a>
        <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
      </td>
    </tr>
    <? endif; ?>

    <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
    <? if (!empty($nextTitles)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('New Title')?>: </th>
      <td>
        <? foreach($nextTitles as $field): ?>
          <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
        <? endforeach; ?>
      </td>
    </tr>
    <? endif; ?>

    <? if (!empty($prevTitles)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Previous Title')?>: </th>
      <td>
        <? foreach($prevTitles as $field): ?>
          <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
        <? endforeach; ?>
      </td>
    </tr>
    <? endif; ?>

    <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
    <? if (isset($authors['main']) && !empty($authors['main'])): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Main Author')?>: </th>
      <td property="author"><a href="<?=$this->record($this->driver)->getLink('author', $authors['main'])?>"><?=$this->escapeHtml($authors['main'])?></a></td>
    </tr>
    <? endif; ?>

    <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Corporate Author')?>: </th>
      <td property="creator"><a href="<?=$this->record($this->driver)->getLink('author', $authors['corporate'])?>"><?=$this->escapeHtml($authors['corporate'])?></a></td>
    </tr>
    <? endif; ?>

    <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Other Authors')?>: </th>
      <td>
        <? $i = 0; foreach ($authors['secondary'] as $field): ?><?=($i++ == 0)?'':', '?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span><? endforeach; ?>
      </td>
    </tr>
    <? endif; ?>

    <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
      <tr valign="top">
        <th><?=$this->transEsc('Format')?>: </th>
        <td><?=$this->record($this->driver)->getFormatList()?></td>
      </tr>
    <? endif; ?>

    <?// Primo Specific Code - get author, source, collection, languages, issn, and subjects
      // Primo does not differentiate between primary and secondary authors. It simply 
      // lists them in the API response
    ?>
    <? $creators = $this->driver->getCreators(); if (!empty($creators) && !empty($creators[0])): ?>
    <tr valign="top">
      <? if(count($creators)>1): ?>
        <th><?=$this->transEsc('Author/Creators')?></th>
      <? else: ?>
        <th><?=$this->transEsc('Author/Creator')?>: </th>
      <? endif; ?>
      <td>
        <? foreach ($creators as $key => $creator): ?>
        <div class="subjectLine" property="keywords">
            <a title="<?=$this->escapeHtml($creator)?>" href="<?=$this->record($this->driver)->getLink('author', $creator)?>" class="subjectHeading"><?=$this->escapeHtml($creator)?></a>
        </div>
        <? endforeach; ?>
      </td>
    </tr>
    <? endif; ?>
    <? $source = $this->driver->getSource(); if (!empty($source)): ?>
      <tr valign="top">
        <th><?=$this->transEsc('Source')?>: </th>
        <td><?=$source ?></td>
      </tr>
    <? endif; ?>

    <? $collection = $this->driver->getCollection(); if (!empty($collection)): ?>
      <? $splitter = explode("<img", $collection); ?>
      <tr valign="top">
        <th><?=$this->transEsc('Collection')?>: </th>
        <td><?=$splitter[0] ?></td>
      </tr>
    <? endif; ?>

    <? $langs = $this->driver->getLanguages(); if (!empty($langs) && !empty($langs[0])): ?>
      <tr valign="top">
        <th><?=$this->transEsc('Language')?>: </th>
        <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
      </tr>
    <? endif; ?>

    <? $issns = $this->driver->getISSNs(); if (!empty($issns)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('ISSN')?>: </th>
      <td>
        <? foreach ($issns as $key => $issn): ?>
        <div class="subjectLine" property="keywords">
            <a title="<?=$this->escapeHtml($issn)?>" href="<?=$this->record($this->driver)->getLink('issn', $issn)?>" class="subjectHeading"><?=$this->escapeHtml($issn)?></a>
        </div>
        <? endforeach; ?>
      </td>
    </tr>
    <? endif; ?>

    <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Subjects')?>: </th>
      <td>
        <? foreach ($subjects as $key => $subject): ?>
        <div class="subjectLine" property="keywords">
            <a title="<?=$this->escapeHtml($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', preg_replace('/ -- /', "", $subject))?>" class="subjectHeading"><?=$this->escapeHtml($subject)?></a>
        </div>
        <? endforeach; ?>
      </td>
    </tr>
    <? endif; ?>
    <? // End Primo specific code ?>

    <?
        $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
        // Account for replace_other_urls setting
        $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
    ?>
    <? if (!empty($urls) || $openUrl): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Online Access')?>: </th>
      <td>
        <? foreach ($urls as $current): ?>
          <a href="<?=$this->escapeHtml($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
        <? endforeach; ?>
        <? if ($openUrl): ?>
          <?=$this->openUrl($openUrl)?><br/>
        <? endif; ?>
      </td>
    </tr>
    <? endif; ?>

    <? $recordLinks = $this->driver->getAllRecordLinks(); if (!empty($recordLinks)): ?>
      <tr valign="top">
        <th><?=$this->transEsc('Related Items')?></th>
        <td>
          <? foreach ($recordLinks as $recordLink): ?>
            <?=$this->transEsc($recordLink['title'])?>:
            <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
          <? endforeach; ?>
        </td>
      </tr>
    <? endif; ?>

    <? $tagList = $this->driver->getTags(); ?>
    <tr valign="top">
      <th><?=$this->transEsc('Tags')?>: </th>
      <td>
        <span style="float:right;">
          <a href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" class="tool add tagRecord controller<?=$this->record($this->driver)->getController()?>" title="<?=$this->transEsc('Add Tag')?>" id="tagRecord"><?=$this->transEsc('Add Tag')?></a>
        </span>
        <div id="tagList">
          <? if (count($tagList) > 0): ?>
            <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
          <? else: ?>
            <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
          <? endif; ?>
        </div>
      </td>
    </tr>
  </table>
  <?/* End Main Details */?>
</div>

<div class="span-4 last">
  <? /* Display thumbnail if appropriate: */ ?>
  <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
  <? if ($mediumThumb): ?>
    <? if ($largeThumb): ?><a href="<?=$this->escapeHtml($largeThumb)?>"><? endif; ?>
      <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtml($mediumThumb);?>"/>
    <? if ($largeThumb): ?></a><? endif; ?>
  <? else: ?>
    <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
  <? endif; ?>

  <? /* Display qrcode if appropriate: */ ?>
  <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
  <? if($QRCode): ?>
    <img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtml($QRCode);?>"/>
  <? endif; ?>

  <? /* Display the lists that this record is saved to */ ?>
  <div class="savedLists info hide" id="savedLists">
    <strong><?=$this->transEsc("Saved in")?>:</strong>
  </div>

  <?=$this->record($this->driver)->getPreviews()?>
</div>

<div class="clear"></div>
